---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true

  GitHubRepositoryUrl:
    Type: String

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: {Service: [amplify.amazonaws.com]}
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'amplify:*'
                Resource:
                  - '*'

  AmplifySite:
    Type: AWS::Amplify::App
    Properties:
      Name: athena-guide
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Repository: !Ref GitHubRepositoryUrl
      OauthToken: !Ref GitHubToken
      EnvironmentVariables:
        - Name: BASE_URL
          Value: https://athena.guide
        - Name: _CUSTOM_IMAGE
          Value: amplify:al2023
        - Name: _BUILD_TIMEOUT
          Value: 5
      BuildSpec: |-
        version: 1
        frontend:
          phases:
            build:
              commands:
                - nvm use 20
                - yarn install
                - yarn build
          artifacts:
            baseDirectory: .vitepress/dist
            files:
              - '**/*'
          customHeaders:
            - pattern: '**/*'
              headers:
                - key: Strict-Transport-Security
                  value: max-age=31536000; includeSubDomains
                - key: X-Frame-Options
                  value: SAMEORIGIN
                - key: X-XSS-Protection
                  value: 1; mode=block
                - key: X-Content-Type-Options
                  value: nosniff
          cache:
            paths:
              - node_modules/**/*

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifySite.AppId
      EnableAutoBuild: true

  AmplifyStagingBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: staging
      AppId: !GetAtt AmplifySite.AppId
      EnableAutoBuild: true

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: athena.guide
      AppId: !GetAtt AmplifySite.AppId
      SubDomainSettings:
        - Prefix: ''
          BranchName: master
        - Prefix: the
          BranchName: master

  GSuiteRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: athena.guide.
      RecordSets:
        - Name: athena.guide.
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - '"google-site-verification=fwCsjkrgsTB7xARFI8tSgML-kP_S1K-TVjpS2cNbxrk"'
        - Name: athena.guide.
          Type: MX
          TTL: '300'
          ResourceRecords:
            - '1 aspmx.l.google.com.'
            - '5 alt1.aspmx.l.google.com.'
            - '5 alt2.aspmx.l.google.com.'
            - '10 aspmx2.googlemail.com.'
            - '10 aspmx3.googlemail.com.'
