---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true

  GitHubRepositoryUrl:
    Type: String

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: {Service: [amplify.amazonaws.com]}
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'amplify:*'
                Resource:
                  - '*'

  AmplifySite:
    Type: AWS::Amplify::App
    Properties:
      Name: athena-guide
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Repository: !Ref GitHubRepositoryUrl
      OauthToken: !Ref GitHubToken

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifySite.AppId
      EnableAutoBuild: true

  AmplifyStagingBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: staging
      AppId: !GetAtt AmplifySite.AppId
      EnableAutoBuild: true

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: athena.guide
      AppId: !GetAtt AmplifySite.AppId
      SubDomainSettings:
        - Prefix: ''
          BranchName: master
        - Prefix: the
          BranchName: master

  GSuiteRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: athena.guide.
      RecordSets:
        - Name: athena.guide.
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - '"google-site-verification=fwCsjkrgsTB7xARFI8tSgML-kP_S1K-TVjpS2cNbxrk"'
        - Name: athena.guide.
          Type: MX
          TTL: '300'
          ResourceRecords:
            - '1 aspmx.l.google.com.'
            - '5 alt1.aspmx.l.google.com.'
            - '5 alt2.aspmx.l.google.com.'
            - '10 aspmx2.googlemail.com.'
            - '10 aspmx3.googlemail.com.'
