---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  GitHubToken:
    Type: String
    NoEcho: true

  GitHubRepositoryUrl:
    Type: String

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: {Service: [amplify.amazonaws.com]}
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'amplify:*'
                Resource:
                  - '*'

  AmplifySite:
    Type: AWS::Amplify::App
    Properties:
      Name: athena-guide
      IAMServiceRole: !GetAtt AmplifyRole.Arn
      Repository: !Ref GitHubRepositoryUrl
      OauthToken: !Ref GitHubToken
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            build:
              commands:
                - yarn install test generate
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          customHeaders:
            - pattern: '**/*'
              headers:
                - key: Strict-Transport-Security
                  value: max-age=31536000; includeSubDomains
                - key: X-Frame-Options
                  value: SAMEORIGIN
                - key: X-XSS-Protection
                  value: 1; mode=block
                - key: X-Content-Type-Options
                  value: nosniff
          cache:
            paths:
              - node_modules/**/*

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifySite.AppId
      EnableAutoBuild: true
